### PR TITLE
Add information in slack message

### PR DESCRIPTION
**Pull request by JulietteVl**
The rates are still to be added. Precisions and units may be changed, as
well as the structure of the message. Here is preview:

image

### CODE REVIEW

**Comment by JulienPeloton** [comment]
I like the formatting! Some suggestions:
- For the apparent  magnitude, we would need to quote the band.
- I would also add the kilonova score for the `classifier` filter, and information on the closest Mangrove galaxy for the `magrove` filter.

**Comment by JulietteVl** [comment]
image

I will check the results from the rate

**Comment by JulietteVl** [comment]
The values seem to match, except I have also been using the values that don't pass the quality cuts, so more often than not the website display a null value for the rate and I don't. Should I change it? I think it make sense to use them as the classifier does, but on the other hand it gives weird values sometimes (like -2103.03 mag/day in r for ZTF21aaublej)

**Review by JulienPeloton — COMMENTED** [review]
Thanks @JulietteVl, the initial code was very interesting! 

However, I reviewed the code, and found several bugs:
- The rate computation was not correct. The rate must be computed between the `last` and `last-1` measurements from the same band.
- You were using the dummy variable `i` in several nested places (hence with a risk of being  overwritten).
- Inside `pandas_udf`, Spark is casting `None` in `NaN`. Hence, masks like `col != None` are not understood. One must use `~np.isnan(col)`.

These bugs have been corrected (I directly pushed in the branch - so do not forget to pull modifications).

I also simplified the constructor of the filter. The concatenated columns `c<quantity>` obtained from [concat_col](https://github.com/astrolabsoftware/fink-science/blob/e09507cf80ed4a2af482d42f1c2ee2c6c66ace0d/fink_science/utilities.py#L23) contains the history AND the last (new) measurement, hence you do not need to pass e.g. `jd` and `cjd`.

I also re-organise the text of the Slack message, adding new information. It now looks:

Screenshot 2021-04-18 at 22 55 32

Finally, I fixed [PEP8](https://pep8.org/) issues.

I checked on several days, but could you check the new code to make sure I've not forgotten things?

**Comment by JulietteVl** [comment]
Hi @JulienPeloton,
Thanks for your help!
I checked the code and the results and everything looks fine to me.

**Comment by JulienPeloton** [comment]
OK, merging! Thanks for the work!

**Pull request merged**
