### PR TITLE
Second kilonova filter, using cross-match with mangrove

### PR DESCRIPTION
**Pull request by JulietteVl**
The cuts and thresholds still have to be more selective. There are 500 alerts/night left on average (April) in the early_kn filter, nearly as much for amateur.

### CODE REVIEW

**Comment by JulietteVl** [comment]
image
I retrieved the host galaxies, but I need to run some more checks to make sure everything is coherent.

**Comment by JulienPeloton** [comment]
For the alert-host distance, shouldn't be `Kpc` instead of `Mpc`?

**Comment by JulietteVl** [comment]
Given that the ZTF sees up to an apparent magnitude `m_max = 20.5` (well in theory, sometimes I get more)
And `M = m+5-5log10(dpc) = m-1-5log10(dMpc)`
And working on the assumption that a kilonova has an absolute magnitude superior to `M_min = 15`

Either I made a mistake, either we can only find candidates in galaxies that are less than 8Mpc away :')

**Comment by JulienPeloton** [comment]
Hum, you should probably redirect this question in the Slack channel. Grandma people will better answer this.

**Comment by JulietteVl** [comment]
image

A minimum threshold is not required at this range because `0.01/200 * 180/pi * 3600 = 10''`

**Comment by JulienPeloton** [comment]
Great, 10 arcseconds (=10 pixels in the sky map) is about 4 times the PSF scale, so the distance is resolved.

**Comment by JulienPeloton** [comment]
@JulietteVl Can you resolve the (small) conflict with the master before I merge this branch? Thanks!

**Comment by JulienPeloton** [comment]
Thanks, merging!

**Pull request merged**
