### PR TITLE
Remove mangrove galaxy id

### PR DESCRIPTION
**Pull request by JulietteVl**
We could let it when there is no name but I don't know if it's an efficient way of retrieving the information.

Reminder of the available names:
image

### CODE REVIEW

**Comment by JulienPeloton** [comment]
Thanks - are `GWGC_name` and `HyperLEDA_name` names are always equivalent?

**Comment by JulietteVl** [comment]
image

No always

**Comment by JulietteVl** [comment]
Number of names != None:
Hyperleda: 613 407
2Mass: 540 119
GWGC: 52 260
SDSS: 14

And inside the 230Mpc limit: 
Hyperleda: 234 765
2Mass: 186 647
GWGC: 51 700
SDSS: 3

So 2Mass is not bad but we might have a few more names on average if we change to hyperleda

I think the best would be to use one or the other depending on available names, that would cover 294860 galaxies in 230Mpc so 99.8% of the 295341 galaxies

**Comment by JulienPeloton** [comment]
I would suggest to display the two then ;-) (Hyperleda and 2Mass)

**Comment by JulietteVl** [comment]
image

**Review by JulienPeloton — APPROVED** [review]
Thanks @JulietteVl ! I will merge it

**Pull request merged**
