### PR TITLE
[Kilonova] add link to TNS, and change position units to degrees

### LINKED ISSUE #25: Add conesearch to TNS in the KN filter
Follow-up data are usually posted to TNS (other broker reports, spectra, ...). For KN, these additional information are important especially to discard any false alert.

Action item: add a link to TNS (conesearch) in the Slack message for KN candidate

### LINKED ISSUE #26: [Kilonova] Change position units to degree
We currently use DMS for RA/Dec/GLAT which is not supported on all external web services. Let's use degrees instead.

### PR DESCRIPTION
**Pull request by JulienPeloton**
Closes #25
Closes #26

Screenshot 2021-04-27 at 08 13 45

### CODE REVIEW

**Comment by JulietteVl** [comment]
Thank you Julien! I think everything is correct, I would also add the equatorial coordinates in format HH MM SS.SS [+-]DD MM SS.S as Sergey suggested it would be the most convenient, unless you think it makes too much things.
image
Maybe it would be better to only use white spaces as separators, I will ask him

**Comment by JulietteVl** [comment]
image

**Review by JulietteVl — APPROVED** [review]

**Comment by JulienPeloton** [comment]
Thanks @JulietteVl ! The new **Position** box is difficult to read -- I would suggest for example:

```
*RA/Dec:*
- [hours, deg]: 15 35 34.27, 5 23 32
- [deg, deg]: 233.8927718, 5.3922241
*Galactic latitude:*
- [deg]: 45.3344686
```

Work that work for the layout? (i.e. it would display a single line for each bullet point?)

**Comment by JulietteVl** [comment]
I will give it a try right now!

**Comment by JulietteVl** [comment]
image
This part still doesn't fit, I will try to see if we can get something a bit more good-looking with indents or something.

**Comment by JulienPeloton** [comment]
and if you replace [hours, deg] by [HH, DD]?

**Comment by JulietteVl** [comment]
Actually it passed with `[hours, deg]`, I just forgot to remove the newline character...
I'll wrap that up and push it

**Comment by JulietteVl** [comment]
image
Do you see anything else that we could want to change?

**Comment by JulienPeloton** [comment]
All good! Thanks, you can merge it - I will make a release tonight.

**Pull request merged**
